// One-off script: seeds the master catalog (Lab / CatalogSection /
// CatalogItem) from data/master-catalog.seed.json, so the app has real
// data to snapshot into the first InventoryDocument. Run once via
// `npm run db:seed` after the database has been migrated.
//
// The JSON file was generated by parsing the original RASL Form 19 table
// directly (two labs, ~90 chemicals total) - see README.md "Master catalog
// seed data" for how it was produced and what to double-check before
// relying on it.
import { prisma } from "../src/lib/prisma";
import catalogData from "../data/master-catalog.seed.json";

interface SeedItem {
  name: string;
  brand: string | null;
  catalogNo: string | null;
  quantityRaw: string;
  footnote: boolean;
  sortOrder: number;
}

interface SeedSection {
  label: string;
  level: number;
  sortOrder: number;
  items: SeedItem[];
}

interface SeedLab {
  name: string;
  sortOrder: number;
  sections: SeedSection[];
}

async function main() {
  const labs = (catalogData as { labs: SeedLab[] }).labs;

  let labCount = 0;
  let sectionCount = 0;
  let itemCount = 0;

  for (const lab of labs) {
    const createdLab = await prisma.lab.create({
      data: { name: lab.name, sortOrder: lab.sortOrder },
    });
    labCount++;

    for (const section of lab.sections) {
      const createdSection = await prisma.catalogSection.create({
        data: {
          labId: createdLab.id,
          parentId: null,
          label: section.label,
          level: section.level,
          sortOrder: section.sortOrder,
        },
      });
      sectionCount++;

      for (const item of section.items) {
        await prisma.catalogItem.create({
          data: {
            sectionId: createdSection.id,
            name: item.name,
            brand: item.brand,
            catalogNo: item.catalogNo,
            quantityRaw: item.quantityRaw,
            footnote: item.footnote,
            sortOrder: item.sortOrder,
          },
        });
        itemCount++;
      }
    }
  }

  console.log(`Seeded ${labCount} labs, ${sectionCount} sections, ${itemCount} chemicals.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
